# Generated by Django 4.1.7 on 2024-03-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_category_created_date_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='number of Stock'),
        ),
    ]
