# Generated by Django 4.1.7 on 2024-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Baby Size', 'Baby Size'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-Large', 'X-Large'), ('XX-Large', 'XX-Large'), ('XXX-Large', 'XXX-Large')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
