# Generated by Django 4.1.7 on 2024-04-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0007_product_delivery_product_pay_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minBuy',
            field=models.IntegerField(default=1, verbose_name='minBuy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='number of Available Stock'),
        ),
    ]
