# Generated by Django 4.1.7 on 2024-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
