# Generated by Django 4.1.7 on 2024-03-16 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='code',
            field=models.CharField(default=datetime.datetime(2024, 3, 16, 21, 8, 53, 841261, tzinfo=datetime.timezone.utc), max_length=25),
            preserve_default=False,
        ),
    ]
