# Generated by Django 4.1.7 on 2024-04-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_sizes_remove_product_size_product_size'),
        ('cart', '0014_rename_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shelf.sizes'),
            preserve_default=False,
        ),
    ]
