# Generated by Django 4.1.7 on 2023-09-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isPastor', to=settings.AUTH_USER_MODEL),
        ),
    ]
