# Generated by Django 4.1.7 on 2024-03-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profilepic_date_joined_profilepic_update_fields_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pastor',
        ),
    ]
